triage_task:
  description: >
    Analyze the following customer query to determine the type:
    Customer Query: {current_query}

    Previous conversation: {conversation_history}

    Determine if this is:
    1. A claim-related query (about existing claims, filing new claims, claim status)
    2. A policy-related query (about coverage, terms, conditions)
    3. A general inquiry that needs more information

    Return ONLY ONE of these exact categories: "claim", "policy", or "general"
  expected_output: >
    The category of the user query (claim, policy, or general)
  agent: triage_specialist

clarification_task:
  description: >
    The customer query was categorized as general or unclear:
    Query: {current_query}
    
    Previous conversation: {conversation_history}
    
    Generate a helpful response that:
    1. Acknowledges their query
    2. Asks for specific clarification
    3. Offers suggestions about whether they need help with claims or policy information
    
    Be conversational and helpful while guiding them to provide more details.
  expected_output: >
    A response asking for clarification
  agent: triage_specialist

policy_task:
  description: >
    Answer this policy-related customer query:
    Query: {current_query}
            
    Previous conversation: {conversation_history}
            
    First, determine what type of policy they're asking about (auto, home, motocycle, life, etc.).
    Then use the search_policy_doc tool to look up relevant information.
            
    Provide a helpful, detailed response about the policy. Include specific coverage
    details, limitations, and any other relevant information.
  expected_output: > 
    A helpful response to the customer's policy query
  agent: policy_specialist

claim_task:
  description: >
    Process this claim-related customer query:
    Query: {current_query}
    policy number: {policy_number}
    
    Previous conversation: {conversation_history}
    
    If you have a policy number, 
    - use the search_policy_details_by_policy_number tool to retrieve customer profile and policy information.
    - use the search_claim_by_policy_number tool to retrieve existing claim information.
    
    Provide a helpful, detailed response about their claim. If you don't have their
    policy_number, explain that you need it to access their claim information.
  expected_output: >
    A helpful response to the customer's claim query
  agent: claim_specialist

